require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*' 
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Style/ClassVars:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false