AllCops:
  Exclude:
    - 'bin/**/*' 
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Style/ClassVars:
  Enabled: false