# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: postgres

      - image: redis

    working_directory: ~/repo

    environment:
      PG_HOST: localhost
      PG_USER: postgres
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@127.0.0.1:5432/flaky_spec_examples_test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn install

      - run: sudo apt install -y postgresql-client || true

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:reset db:migrate

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec
